@startuml
'https://plantuml.com/activity-diagram-beta
/'未登录的租客无法使用评论房间的功能，如果未登录的租客点击评论按钮会提示用户未登录。租客需要登录后，并且要退房后才能使用评论房间的功能，发表对房间的评论。
  租客登录客户端网站后，在房间详情页面输入评论信息，点击评论按钮，系统检查评论内容是否为空，如果评论内容为空，提示错误信息。如果评论内容不为空，则判断用户是否登录，如果用户未登录，提示用户先去登录，如果用户已登录，则保存评论数据到数据库，并提示评论成功，刷新评论内容。
'/
start
    :租客登录客户端网站;
    :进入房间详情页面;
    :输入评论信息;
    :点击评论按钮;
    :系统检查评论内容是否为空;
    if (评论内容为空) then (是)
        :提示错误信息;
    else (评论内容不为空)
        :判断用户是否登录;
        if (用户未登录) then (是)
        :提示用户先去登录;
        else (用户已登录)
        :保存评论数据到数据库;
        :提示评论成功;
        :刷新评论内容;
        endif
    endif
stop

@enduml
