@startuml
'https://plantuml.com/activity-diagram-beta
/'
  租客登录客户端网站后，在民宿房间详情页面选择预定信息后，点击预订，系统检查用户是否登录，如果用户未登录则提示用户先去登录，如果用户已登录，系统则查询该房间是否允许被预定，系统检查所选择的时间是否符合要求，不符合要求则返回错误信息，符合要求则显示预约成功。系统生成订单信息并保存到数据库，返回订单信息，跳转到订单页面显示订单信息。
'/
start
:租客登录客户端网站;
:选择预定信息;
:点击预订;
if(用户是否登录) then (是)
  :查询该房间是否允许被预定;
  if(所选择的时间是否符合要求) then (是)
    :显示预约成功;
    :生成订单信息并保存到数据库;
    :返回订单信息;
    :跳转到订单页面显示订单信息;
  else (否)
    :返回错误信息;
  endif
else (否)
  :提示用户先去登录;
stop

@enduml
