@startuml
'https://plantuml.com/activity-diagram-beta
/'分用户和系统两个角色，用户点击某个民宿房间的图标，系统查询数据库，返回查询结果，页面跳转到房间的详细信息页面，页面显示房间的详细信息'/
start
:用户点击某个民宿房间的图标;
:系统查询数据库;
:返回查询结果;
:页面跳转到房间的详细信息页面;
:页面显示房间的详细信息;
stop

@enduml
