@startuml
'https://plantuml.com/activity-diagram-beta
/'普通用户在注册页面输入注册信息，包括用户名、手机号、密码邮箱、身份证，系统检查手机号，邮箱、身份证格式是否正确，不正确则提示格式错误，点击注册，系统检查注册信息的格式是否正确，不正确则提示相关的错误信息，正确则将用户的注册信息提交至后台，后台验证用户名的合法性后，若不合法则提示用户名已存在，若合法，则保存到数据库，返回登录页面。'/
start
:输入注册信息;
if (信息格式是否正确) then (是)
  :检查用户名是否存在;
  if (用户名是否存在) then (是)
    :提示用户名已存在;
  else (否)
    :保存注册信息;
    :返回登录页面;
  endif
else (否)
  :提示信息格式错误;
endif
stop

@enduml
