@startuml
'https://plantuml.com/activity-diagram-beta

/'
用户在登录页面输入账号信息，包括手机号和密码，点击登录，系统检查手机号和密码的数据格式是否正确，不正确则提示相关错误信息，正确则从数据库获取用户数据检查账号信息，比较手机号和密码是否一致，如果一致，则生成生成springsecurity认证对象并返回用户信息，页面跳转到网站首页面，在首页面显示用户信息。如果账号密码不一致，则提示错误信息，让用户重新登录。
'/
start
:输入账号信息;
:点击登录;
if (账号信息格式正确) then (是)
    if (账号信息正确) then (是)
        :生成springsecurity认证对象;
        :返回用户信息;
        :跳转到网站首页面;
        :显示用户信息;
    else (否)
        :提示错误信息;
        :重新登录;
    endif
else (否)
    :提示错误信息;
    :重新登录;
@enduml
