@startuml
'https://plantuml.com/use-case-diagram
/'在统计分析模块中，管理员可以查看民宿日报表和民宿月报表'/
left to right direction
skinparam packageStyle rectangle
actor 管理员
rectangle 统计分析模块{
  管理员 -- (查看民宿报表)
  (查看民宿报表) -- (查看民宿日报表)
  (查看民宿报表) -- (查看民宿月报表)
}
@enduml