@startuml
participant Actor
Actor -> AdvertiseController : getAllAdvertise
activate AdvertiseController
AdvertiseController -> UserService : selectUserByUsername
activate UserService
UserService -> UserServiceImpl : selectUserByUsername
activate UserServiceImpl
UserServiceImpl -> UserMapper : selectUserByUsername
activate UserMapper
UserMapper -> DATABASE : selectUserByUsername
activate DATABASE
DATABASE --> UserMapper
deactivate DATABASE
UserMapper --> UserServiceImpl
deactivate UserMapper
UserServiceImpl --> UserService
deactivate UserServiceImpl
UserService --> AdvertiseController
deactivate UserService
return
@enduml