@startuml
participant Actor
Actor -> RoomController : updateRoom
activate RoomController
RoomController -> UserService : selectUserByUsername
activate UserService
UserService --> RoomController
deactivate UserService
RoomController -> RoomService : updateRoom
activate RoomService
RoomService -> RoomServiceImpl : updateRoom
activate RoomServiceImpl

RoomServiceImpl -> RoomMapper : update
activate RoomMapper
RoomMapper -> DATABASE : update
activate DATABASE
DATABASE --> RoomMapper
deactivate DATABASE
RoomMapper --> RoomServiceImpl
deactivate RoomMapper

RoomServiceImpl --> RoomService
deactivate RoomServiceImpl
RoomService --> RoomController
deactivate RoomService
RoomController -> RoomService : queryMyRooms
activate RoomService
RoomService -> RoomServiceImpl : queryMyRooms
activate RoomServiceImpl

RoomServiceImpl -> RoomMapper : queryMyRooms
activate RoomMapper
RoomMapper -> DATABASE : select
activate DATABASE
DATABASE --> RoomMapper
deactivate DATABASE
RoomMapper --> RoomServiceImpl
deactivate RoomMapper

RoomServiceImpl -> UserService : getUserIdByName
activate UserService
UserService --> RoomServiceImpl
deactivate UserService
RoomServiceImpl --> RoomService
deactivate RoomServiceImpl
RoomService --> RoomController
deactivate RoomService
return
@enduml