@startuml
participant Actor
Actor -> RoomController : deleteRoom
activate RoomController
RoomController -> RoomService : deleteRoom
activate RoomService
RoomService --> RoomController
deactivate RoomService
RoomController -> RoomService : queryMyRooms
activate RoomService
RoomService --> RoomController
deactivate RoomService
RoomController -> UserService : selectUserByUsername
activate UserService
UserService -> UserServiceImpl : selectUserByUsername
activate UserServiceImpl
UserServiceImpl --> UserService
deactivate UserServiceImpl
UserService --> RoomController
deactivate UserService
return
@enduml