@startuml
participant Actor
Actor -> RoomController : toRoomList
activate RoomController
RoomController -> UserService : selectUserByUsername
activate UserService
UserService --> RoomController
deactivate UserService
RoomController -> RoomService : queryMyRooms
activate RoomService
RoomService -> RoomServiceImpl : queryMyRooms
activate RoomServiceImpl
RoomServiceImpl -> UserService : getUserIdByName
activate UserService
UserService --> RoomServiceImpl
deactivate UserService
RoomServiceImpl --> RoomService
deactivate RoomServiceImpl
RoomService --> RoomController
deactivate RoomService
return
@enduml