@startuml
participant Actor
Actor -> UserController : toLardlordIndex
activate UserController
UserController -> UserService : selectUserByUsername
activate UserService
UserService -> UserServiceImpl : selectUserByUsername
activate UserServiceImpl

UserServiceImpl -> UserMapper : selectUserByUsername
activate UserMapper
UserMapper -> DATABASE : select
activate DATABASE
DATABASE --> UserMapper
deactivate DATABASE
UserMapper --> UserServiceImpl
deactivate UserMapper

UserServiceImpl --> UserService
deactivate UserServiceImpl
UserService --> UserController
deactivate UserService
return
@enduml