@startuml
participant Actor
Actor -> UserController : deleteUser
activate UserController
UserController -> UserService : selectUserByUsername
activate UserService
UserService -> UserServiceImpl : selectUserByUsername
activate UserServiceImpl
UserServiceImpl --> UserService
deactivate UserServiceImpl
UserService --> UserController
deactivate UserService
UserController -> UserService : deleteUser
activate UserService
UserService -> UserServiceImpl : deleteUser
activate UserServiceImpl
UserServiceImpl --> UserService
deactivate UserServiceImpl
UserService --> UserController
deactivate UserService
return
@enduml