server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/homestay?useSSL=false&serverTimezone=UTC
    username: root
    password: will
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  #redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: lzh01081172
  #热部署配置
  devtools:
    restart:
      enabled: true

# 配置MyBatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#文件映射
file:
  staticAcessPath: '/pic/**'
  uploadFileFolder: 'E:/file/'



