@startuml
'https://plantuml.com/activity-diagram-beta
/'点击广告管理，选择要修改的广告，系统查询该广告，返回广告信息并展示在广告详情页面，用户修改广告信息，点击确定，系统封装广告信息，并保存至数据库，若保存失败，则提示错误信息，若成功则返回广告管理页面'/
start
:点击广告管理;
:选择要修改的广告;
:系统查询该广告;
:返回广告信息并展示在广告详情页面;
:用户修改广告信息;
:点击确定;
:系统封装广告信息;
:保存至数据库;
if (保存失败) then (yes)
  :提示错误信息;
else (no)
  :返回广告管理页面;
endif
stop

@enduml
