@startuml
'https://plantuml.com/activity-diagram-beta
/'点击修改民宿，系统查询该民宿并返回查询结果，跳转到该民宿的详情页面，房东修改民宿信息，点击确定，系统判断民宿地址的合法性，若民宿地址已存在，则返回错误信息，若合法，则返回提示信息：修改成功，最后返回民宿列表页面'/
start

:点击修改民宿;
:系统查询该民宿并返回查询结果;
:跳转到该民宿的详情页面;
:房东修改民宿信息;
:点击确定;
:系统判断民宿地址的合法性;
if (民宿地址已存在) then (是)
    :返回错误信息;
else (否)
    :返回提示信息：修改成功;
endif
:返回民宿列表页面;
stop

@enduml
