@startuml
'https://plantuml.com/activity-diagram-beta
/'点击删除民宿，系统检查民宿是否状态，若处于租用状态，则返回错误信息，该民宿处于被租用状态，无法删除，否则系统删除该民宿，并返回提示信息，删除成功，最后返回删除民宿界面'/
start
:点击删除民宿;
if(民宿状态是否为租用) then (是)
  :返回错误信息;
  stop
else (否)
  :删除民宿;
  :返回提示信息;
  :返回删除民宿界面;
endif
stop

@enduml
