@startuml
'https://plantuml.com/activity-diagram-beta
/'进入查询用户界面，点击删除，系统删除用户，若删除成功，则提示删除成功，并返回用户列表界面；若删除失败，则返回错误信息，同时跳转至用户列表界面'/
start
:进入查询用户界面;
:点击删除;
:系统删除用户;
if (删除成功?) then (是)
  :提示删除成功;
  :返回用户列表界面;
else (否)
  :返回错误信息;
  :跳转至用户列表界面;
endif
stop

@enduml
