@startuml
'https://plantuml.com/activity-diagram-beta
/'进入订单详情页面，点击删除，系统检查订单的状态，若处于未退房状态，则提示删除失败，还未退房，若处于已退房状态，则提示删除成功，返回订单列表界面'/
start
:进入订单详情页面;
:点击删除;
if(订单状态是否为未退房) then (是)
:提示删除失败，还未退房;
else (否)
:提示删除成功;
endif
:返回订单列表界面;

stop

@enduml
