@startuml
'https://plantuml.com/activity-diagram-beta
/'点击批量添加用户，上传表格，检查账号的合法性，若存在不合法的用户则提示批量删除失败，请检查账户名是否存在，若合法，则批量保存到数据库'/
start
:点击批量添加用户;
:上传表格;
:检查账号的合法性;
if (账号是否合法) then (是)
  :批量保存到数据库;
else (否)
  :提示批量删除失败，请检查账户名是否存在;
endif
:返回批量添加页面;
stop

@enduml
