@startuml
'https://plantuml.com/activity-diagram-beta
/'点击添加民宿，输入民宿信息，系统检查民宿地址的合法性，若不合法，提示民宿地址已被占用，若合法，将民宿保存到数据库，返回添加民宿界面'/
start
:点击添加民宿;
:输入民宿信息;
:系统检查民宿地址的合法性;
if(民宿地址合法?) then (是)
    :将民宿保存到数据库;
    :返回添加民宿界面;
else (否)
    :提示民宿地址已被占用;
    :返回添加民宿界面;
endif

stop

@enduml
