@startuml
'https://plantuml.com/activity-diagram-beta
/'点击添加用户，输入用户信息，系统检查手机号，邮箱、身份证格式是否正确，不正确则提示格式错误，点击注册，系统检查注册信息的格式是否正确，不正确则提示相关的错误信息，正确则将用户的注册信息提交至后台，后台验证用户名的合法性后，若不合法则提示用户名已存在，若合法，则保存到数据库，返回添加用户页面。'/
start
:输入用户信息;
:系统检查手机号，邮箱、身份证格式是否正确;
if (格式不正确) then (是)
:提示格式错误;
else (否)
:点击注册;
:系统检查注册信息的格式是否正确;
if (格式不正确) then (是)
:提示相关的错误信息;
else (否)
:将用户的注册信息提交至后台;
:后台验证用户名的合法性;
if (不合法) then (是)
:提示用户名已存在;
else (否)
:保存到数据库;
:返回添加用户页面;
endif
endif
endif
stop

@enduml
